# Generated by Django 5.2.5 on 2025-08-22 14:24

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('id_tg', models.BigIntegerField(db_column='id_tg', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('email', models.EmailField(db_column='mail', max_length=100, unique=True)),
                ('password', models.TextField(db_column='password')),
                ('mail_mg', models.CharField(blank=True, db_column='mail_mg', max_length=100, null=True)),
                ('confirm', models.BooleanField(db_column='confirm', default=False)),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
                'db_table': 'curator',
                'managed': False,
            },
            managers=[
                ('objects', users.models.CuratorManager()),
            ],
        ),
    ]
