# Generated by Django 5.2.5 on 2025-08-22 08:55

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curator',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id_tg', models.BigIntegerField(db_column='id_tg', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('email', models.EmailField(db_column='mail', max_length=100, unique=True)),
                ('password', models.TextField(db_column='password')),
                ('mail_mg', models.CharField(blank=True, db_column='mail_mg', max_length=100, null=True)),
                ('confirm', models.BooleanField(db_column='confirm', default=False)),
            ],
            options={
                'verbose_name': 'Куратор',
                'verbose_name_plural': 'Кураторы',
                'db_table': 'curator',
                'managed': False,
            },
            managers=[
                ('objects', core.models.CuratorManager()),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id_assignment', models.AutoField(db_column='id_assignment', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'db_table': 'assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(db_column='id_department', primary_key=True, serialize=False)),
                ('department', models.CharField(db_column='department', max_length=10)),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(db_column='id_report', primary_key=True, serialize=False)),
                ('timestamp_start', models.DateTimeField(db_column='timestamp_start')),
                ('timestamp_end', models.DateTimeField(blank=True, db_column='timestamp_end', null=True)),
                ('report_text', models.TextField(blank=True, db_column='report_text', null=True)),
                ('report_url', models.TextField(blank=True, db_column='report_url', null=True)),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(db_column='id_role', primary_key=True, serialize=False)),
                ('role', models.CharField(db_column='role', max_length=100)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(db_column='id_status', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(db_column='id_subject', primary_key=True, serialize=False)),
                ('subject', models.CharField(db_column='subject', max_length=15)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'subject',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.CharField(db_column='id_task', max_length=100, primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField(db_column='deadline')),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.TextField(db_column='description')),
                ('report', models.TextField(db_column='report')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'task',
                'managed': False,
            },
        ),
    ]
