# Generated by Django 5.2.5 on 2025-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id_department', models.AutoField(db_column='id_department', primary_key=True, serialize=False)),
                ('department', models.CharField(db_column='department', max_length=10)),
            ],
            options={
                'verbose_name': 'Отдел',
                'verbose_name_plural': 'Отделы',
                'db_table': 'department',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.AutoField(db_column='id_role', primary_key=True, serialize=False)),
                ('role', models.CharField(db_column='role', max_length=100)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id_status', models.AutoField(db_column='id_status', primary_key=True, serialize=False)),
                ('status', models.CharField(db_column='status', max_length=100)),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id_subject', models.AutoField(db_column='id_subject', primary_key=True, serialize=False)),
                ('subject', models.CharField(db_column='subject', max_length=15)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'db_table': 'subject',
                'managed': False,
            },
        ),
    ]
