COMPLETED_STATUS = 1
COMPLETED_LATE_STATUS = 2
NOT_COMPLETED_STATUS = 3
CANCELLED_STATUS = 4
ASSIGNMENT_ERROR_STATUS = 5

COMPLETED_STATUSES = (COMPLETED_STATUS, COMPLETED_LATE_STATUS)
EXCLUDE_FROM_TOTAL_STATUSES = (CANCELLED_STATUS, ASSIGNMENT_ERROR_STATUS)
