# Generated by Django 5.2.5 on 2025-08-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id_assignment', models.AutoField(db_column='id_assignment', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Назначение',
                'verbose_name_plural': 'Назначения',
                'db_table': 'assignment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id_report', models.AutoField(db_column='id_report', primary_key=True, serialize=False)),
                ('timestamp_start', models.DateTimeField(db_column='timestamp_start')),
                ('timestamp_end', models.DateTimeField(blank=True, db_column='timestamp_end', null=True)),
                ('report_text', models.TextField(blank=True, db_column='report_text', null=True)),
                ('report_url', models.TextField(blank=True, db_column='report_url', null=True)),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'db_table': 'report',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id_task', models.CharField(db_column='id_task', max_length=100, primary_key=True, serialize=False)),
                ('deadline', models.DateTimeField(db_column='deadline')),
                ('name', models.CharField(db_column='name', max_length=200)),
                ('description', models.TextField(db_column='description')),
                ('report', models.TextField(db_column='report')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'task',
                'managed': False,
            },
        ),
    ]
