from typing import FrozenSet

ROLE_CURATOR_STANDARD = 1
ROLE_CURATOR_SENIOR = 2
ROLE_CURATOR_PERSONAL = 3
ROLE_CHAT_MANAGER = 4
ROLE_MENTOR_STANDARD = 5
ROLE_MENTOR_PERSONAL = 6
ROLE_LEADER = 7
ROLE_OKK = 8
ROLE_SENIOR_MANAGER = 9


ADMIN_ROLE_IDS: FrozenSet[int] = frozenset({
    ROLE_LEADER,
    ROLE_SENIOR_MANAGER
})

MANAGER_ROLE_IDS: FrozenSet[int] = frozenset({
    ROLE_CHAT_MANAGER,
    ROLE_MENTOR_STANDARD,
    ROLE_MENTOR_PERSONAL,
    ROLE_LEADER,
    ROLE_OKK,
    ROLE_SENIOR_MANAGER
})

MENTOR_ROLE_IDS: FrozenSet[int] = frozenset({
    ROLE_MENTOR_STANDARD,
    ROLE_MENTOR_PERSONAL
})

ROLE_TO_ALLOWED_MENTOR_ROLE_IDS = {
    ROLE_CURATOR_STANDARD: {ROLE_MENTOR_STANDARD},
    ROLE_CURATOR_SENIOR:   {ROLE_MENTOR_PERSONAL},
    ROLE_CURATOR_PERSONAL: {ROLE_MENTOR_PERSONAL},
}
